"""
streamlit_app.py — Streamlit dashboard for Job Market ETL Pipeline.

This app reads the SQLite database generated by main.py and displays:
- KPI summary
- Top job titles
- Top companies
- Remote breakdown
- Salary summary
- Raw clean job records
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pandas as pd
import streamlit as st


DB_PATH = Path("jobs.db")
CSV_FALLBACK_PATH = Path("output/jobs_clean.csv")


st.set_page_config(
    page_title="Job Market ETL Dashboard",
    page_icon="📊",
    layout="wide",
)


@st.cache_data(show_spinner=False)
def load_jobs_from_sqlite(db_path: str) -> pd.DataFrame:
    """
    Load jobs from SQLite database.
    """
    query = """
        SELECT
            id,
            title,
            seniority_level,
            company,
            city,
            region,
            remote_flag,
            salary_min,
            salary_max,
            salary_currency,
            date_posted,
            source,
            url,
            description,
            status,
            first_seen,
            last_seen
        FROM jobs
        WHERE status IN ('active', 'incomplete')
        ORDER BY last_seen DESC, id DESC;
    """

    with sqlite3.connect(db_path) as conn:
        df = pd.read_sql_query(query, conn)

    return prepare_dataframe(df)


@st.cache_data(show_spinner=False)
def load_jobs_from_csv(csv_path: str) -> pd.DataFrame:
    """
    Load jobs from CSV fallback.
    """
    df = pd.read_csv(csv_path)
    return prepare_dataframe(df)


def prepare_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Prepare data types for dashboarding.
    """
    if df.empty:
        return df

    for col in ["date_posted", "first_seen", "last_seen"]:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")

    if "remote_flag" in df.columns:
        df["remote_flag"] = df["remote_flag"].astype(bool)

    if "salary_min" in df.columns and "salary_max" in df.columns:
        df["salary_midpoint"] = (
            pd.to_numeric(df["salary_min"], errors="coerce")
            + pd.to_numeric(df["salary_max"], errors="coerce")
        ) / 2

    return df


def load_data() -> pd.DataFrame:
    """
    Load data from SQLite first, then CSV fallback.
    """
    if DB_PATH.exists():
        return load_jobs_from_sqlite(str(DB_PATH))

    if CSV_FALLBACK_PATH.exists():
        return load_jobs_from_csv(str(CSV_FALLBACK_PATH))

    return pd.DataFrame()


def render_kpis(df: pd.DataFrame) -> None:
    """
    Render top-level KPI cards.
    """
    total_jobs = len(df)
    active_jobs = int((df["status"] == "active").sum()) if "status" in df else 0
    incomplete_jobs = (
        int((df["status"] == "incomplete").sum()) if "status" in df else 0
    )
    remote_jobs = int(df["remote_flag"].sum()) if "remote_flag" in df else 0

    col1, col2, col3, col4 = st.columns(4)

    col1.metric("Total Jobs", total_jobs)
    col2.metric("Active Jobs", active_jobs)
    col3.metric("Incomplete Jobs", incomplete_jobs)
    col4.metric("Remote Jobs", remote_jobs)


def render_sidebar_filters(df: pd.DataFrame) -> pd.DataFrame:
    """
    Sidebar filters for source, status, seniority, and search keyword.
    """
    st.sidebar.header("Filters")

    filtered = df.copy()

    if "source" in filtered.columns:
        sources = sorted(filtered["source"].dropna().unique().tolist())
        selected_sources = st.sidebar.multiselect(
            "Source",
            options=sources,
            default=sources,
        )
        filtered = filtered[filtered["source"].isin(selected_sources)]

    if "status" in filtered.columns:
        statuses = sorted(filtered["status"].dropna().unique().tolist())
        selected_statuses = st.sidebar.multiselect(
            "Status",
            options=statuses,
            default=statuses,
        )
        filtered = filtered[filtered["status"].isin(selected_statuses)]

    if "seniority_level" in filtered.columns:
        seniorities = sorted(filtered["seniority_level"].dropna().unique().tolist())
        selected_seniorities = st.sidebar.multiselect(
            "Seniority",
            options=seniorities,
            default=seniorities,
        )
        if selected_seniorities:
            filtered = filtered[
                filtered["seniority_level"].isin(selected_seniorities)
            ]

    search_text = st.sidebar.text_input("Search title/company")

    if search_text:
        search_lower = search_text.lower()
        filtered = filtered[
            filtered["title"].fillna("").str.lower().str.contains(search_lower)
            | filtered["company"].fillna("").str.lower().str.contains(search_lower)
        ]

    return filtered


def render_charts(df: pd.DataFrame) -> None:
    """
    Render dashboard charts using Streamlit native charts.
    """
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Top Job Titles")
        if "title" in df and not df.empty:
            title_counts = df["title"].fillna("Unknown").value_counts().head(10)
            st.bar_chart(title_counts)
        else:
            st.info("No title data available.")

    with col2:
        st.subheader("Top Hiring Companies")
        if "company" in df and not df.empty:
            company_counts = df["company"].fillna("Unknown").value_counts().head(10)
            st.bar_chart(company_counts)
        else:
            st.info("No company data available.")

    col3, col4 = st.columns(2)

    with col3:
        st.subheader("Remote Breakdown")
        if "remote_flag" in df and not df.empty:
            remote_counts = (
                df["remote_flag"]
                .map({True: "Remote", False: "On-site / Unspecified"})
                .value_counts()
            )
            st.bar_chart(remote_counts)
        else:
            st.info("No remote data available.")

    with col4:
        st.subheader("New Jobs by First Seen Date")
        if "first_seen" in df and not df.empty:
            daily_counts = (
                df.dropna(subset=["first_seen"])
                .assign(first_seen_date=lambda x: x["first_seen"].dt.date)
                .groupby("first_seen_date")
                .size()
            )
            st.line_chart(daily_counts)
        else:
            st.info("No date data available.")


def render_salary_section(df: pd.DataFrame) -> None:
    """
    Render salary summary table.
    """
    st.subheader("Salary Summary")

    if df.empty or "salary_midpoint" not in df.columns:
        st.info("No salary data available.")
        return

    salary_df = df.dropna(subset=["salary_midpoint"]).copy()

    if salary_df.empty:
        st.info("Salary data not available in current records.")
        return

    summary = (
        salary_df.groupby(["title", "salary_currency"], dropna=False)
        .agg(
            count=("id", "count"),
            salary_min=("salary_min", "min"),
            salary_median=("salary_midpoint", "median"),
            salary_max=("salary_max", "max"),
        )
        .reset_index()
        .sort_values(["count", "salary_median"], ascending=[False, False])
    )

    st.dataframe(summary, use_container_width=True)


def render_jobs_table(df: pd.DataFrame) -> None:
    """
    Render raw clean jobs table.
    """
    st.subheader("Clean Job Records")

    display_columns = [
        "title",
        "company",
        "seniority_level",
        "region",
        "remote_flag",
        "salary_min",
        "salary_max",
        "salary_currency",
        "date_posted",
        "source",
        "status",
        "url",
    ]

    available_columns = [col for col in display_columns if col in df.columns]

    st.dataframe(
        df[available_columns],
        use_container_width=True,
        hide_index=True,
    )

    csv_bytes = df.to_csv(index=False).encode("utf-8")

    st.download_button(
        label="Download filtered CSV",
        data=csv_bytes,
        file_name="filtered_jobs.csv",
        mime="text/csv",
    )


def main() -> None:
    st.title("📊 Automated Job Market ETL Dashboard")
    st.caption(
        "Portfolio project: scraping, cleaning, deduplication, SQLite loading, and reporting."
    )

    df = load_data()

    if df.empty:
        st.warning(
            "No job data found. Run `python main.py` locally first, "
            "or include `output/jobs_clean.csv` in the deployed repository."
        )
        return

    filtered_df = render_sidebar_filters(df)

    render_kpis(filtered_df)

    st.divider()

    render_charts(filtered_df)

    st.divider()

    render_salary_section(filtered_df)

    st.divider()

    render_jobs_table(filtered_df)


if __name__ == "__main__":
    main()